#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkNCInfoService.WebService
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="WorkNC")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertWorkZone(WorkZone instance);
    partial void UpdateWorkZone(WorkZone instance);
    partial void DeleteWorkZone(WorkZone instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::WorkNCInfoService.WebService.Properties.Settings.Default.WorkNCConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<WorkZone> WorkZones
		{
			get
			{
				return this.GetTable<WorkZone>();
			}
		}
		
		public System.Data.Linq.Table<WorkZoneDetail> WorkZoneDetails
		{
			get
			{
				return this.GetTable<WorkZoneDetail>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.WorkZone")]
	public partial class WorkZone : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Name;
		
		private string _WorkZonePath;
		
		private string _ModelDataProgramer;
		
		private string _NCDataProgramer;
		
		private System.Nullable<System.DateTime> _ProgramDate;
		
		private string _ModelName;
		
		private string _Parts;
		
		private string _PartName;
		
		private string _MachiningTimeTotal;
		
		private int _FactoryId;
		
		private int _MachineId;
		
		private string _Comment;
		
		private System.DateTime _CreateDate;
		
		private string _CreateAccount;
		
		private System.DateTime _ModifiedDate;
		
		private string _ModifiedAccount;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnWorkZonePathChanging(string value);
    partial void OnWorkZonePathChanged();
    partial void OnModelDataProgramerChanging(string value);
    partial void OnModelDataProgramerChanged();
    partial void OnNCDataProgramerChanging(string value);
    partial void OnNCDataProgramerChanged();
    partial void OnProgramDateChanging(System.Nullable<System.DateTime> value);
    partial void OnProgramDateChanged();
    partial void OnModelNameChanging(string value);
    partial void OnModelNameChanged();
    partial void OnPartsChanging(string value);
    partial void OnPartsChanged();
    partial void OnPartNameChanging(string value);
    partial void OnPartNameChanged();
    partial void OnMachiningTimeTotalChanging(string value);
    partial void OnMachiningTimeTotalChanged();
    partial void OnFactoryIdChanging(int value);
    partial void OnFactoryIdChanged();
    partial void OnMachineIdChanging(int value);
    partial void OnMachineIdChanged();
    partial void OnCommentChanging(string value);
    partial void OnCommentChanged();
    partial void OnCreateDateChanging(System.DateTime value);
    partial void OnCreateDateChanged();
    partial void OnCreateAccountChanging(string value);
    partial void OnCreateAccountChanged();
    partial void OnModifiedDateChanging(System.DateTime value);
    partial void OnModifiedDateChanged();
    partial void OnModifiedAccountChanging(string value);
    partial void OnModifiedAccountChanged();
    #endregion
		
		public WorkZone()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(100)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WorkZonePath", DbType="NVarChar(100)")]
		public string WorkZonePath
		{
			get
			{
				return this._WorkZonePath;
			}
			set
			{
				if ((this._WorkZonePath != value))
				{
					this.OnWorkZonePathChanging(value);
					this.SendPropertyChanging();
					this._WorkZonePath = value;
					this.SendPropertyChanged("WorkZonePath");
					this.OnWorkZonePathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModelDataProgramer", DbType="NVarChar(100)")]
		public string ModelDataProgramer
		{
			get
			{
				return this._ModelDataProgramer;
			}
			set
			{
				if ((this._ModelDataProgramer != value))
				{
					this.OnModelDataProgramerChanging(value);
					this.SendPropertyChanging();
					this._ModelDataProgramer = value;
					this.SendPropertyChanged("ModelDataProgramer");
					this.OnModelDataProgramerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NCDataProgramer", DbType="NVarChar(100)")]
		public string NCDataProgramer
		{
			get
			{
				return this._NCDataProgramer;
			}
			set
			{
				if ((this._NCDataProgramer != value))
				{
					this.OnNCDataProgramerChanging(value);
					this.SendPropertyChanging();
					this._NCDataProgramer = value;
					this.SendPropertyChanged("NCDataProgramer");
					this.OnNCDataProgramerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProgramDate", DbType="Date")]
		public System.Nullable<System.DateTime> ProgramDate
		{
			get
			{
				return this._ProgramDate;
			}
			set
			{
				if ((this._ProgramDate != value))
				{
					this.OnProgramDateChanging(value);
					this.SendPropertyChanging();
					this._ProgramDate = value;
					this.SendPropertyChanged("ProgramDate");
					this.OnProgramDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModelName", DbType="NVarChar(100)")]
		public string ModelName
		{
			get
			{
				return this._ModelName;
			}
			set
			{
				if ((this._ModelName != value))
				{
					this.OnModelNameChanging(value);
					this.SendPropertyChanging();
					this._ModelName = value;
					this.SendPropertyChanged("ModelName");
					this.OnModelNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Parts", DbType="NVarChar(100)")]
		public string Parts
		{
			get
			{
				return this._Parts;
			}
			set
			{
				if ((this._Parts != value))
				{
					this.OnPartsChanging(value);
					this.SendPropertyChanging();
					this._Parts = value;
					this.SendPropertyChanged("Parts");
					this.OnPartsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PartName", DbType="NVarChar(100)")]
		public string PartName
		{
			get
			{
				return this._PartName;
			}
			set
			{
				if ((this._PartName != value))
				{
					this.OnPartNameChanging(value);
					this.SendPropertyChanging();
					this._PartName = value;
					this.SendPropertyChanged("PartName");
					this.OnPartNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MachiningTimeTotal", DbType="NChar(10)")]
		public string MachiningTimeTotal
		{
			get
			{
				return this._MachiningTimeTotal;
			}
			set
			{
				if ((this._MachiningTimeTotal != value))
				{
					this.OnMachiningTimeTotalChanging(value);
					this.SendPropertyChanging();
					this._MachiningTimeTotal = value;
					this.SendPropertyChanged("MachiningTimeTotal");
					this.OnMachiningTimeTotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FactoryId", DbType="Int NOT NULL")]
		public int FactoryId
		{
			get
			{
				return this._FactoryId;
			}
			set
			{
				if ((this._FactoryId != value))
				{
					this.OnFactoryIdChanging(value);
					this.SendPropertyChanging();
					this._FactoryId = value;
					this.SendPropertyChanged("FactoryId");
					this.OnFactoryIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MachineId", DbType="Int NOT NULL")]
		public int MachineId
		{
			get
			{
				return this._MachineId;
			}
			set
			{
				if ((this._MachineId != value))
				{
					this.OnMachineIdChanging(value);
					this.SendPropertyChanging();
					this._MachineId = value;
					this.SendPropertyChanged("MachineId");
					this.OnMachineIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comment", DbType="NVarChar(255)")]
		public string Comment
		{
			get
			{
				return this._Comment;
			}
			set
			{
				if ((this._Comment != value))
				{
					this.OnCommentChanging(value);
					this.SendPropertyChanging();
					this._Comment = value;
					this.SendPropertyChanged("Comment");
					this.OnCommentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime NOT NULL")]
		public System.DateTime CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateAccount", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CreateAccount
		{
			get
			{
				return this._CreateAccount;
			}
			set
			{
				if ((this._CreateAccount != value))
				{
					this.OnCreateAccountChanging(value);
					this.SendPropertyChanging();
					this._CreateAccount = value;
					this.SendPropertyChanged("CreateAccount");
					this.OnCreateAccountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedDate", DbType="DateTime NOT NULL")]
		public System.DateTime ModifiedDate
		{
			get
			{
				return this._ModifiedDate;
			}
			set
			{
				if ((this._ModifiedDate != value))
				{
					this.OnModifiedDateChanging(value);
					this.SendPropertyChanging();
					this._ModifiedDate = value;
					this.SendPropertyChanged("ModifiedDate");
					this.OnModifiedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedAccount", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ModifiedAccount
		{
			get
			{
				return this._ModifiedAccount;
			}
			set
			{
				if ((this._ModifiedAccount != value))
				{
					this.OnModifiedAccountChanging(value);
					this.SendPropertyChanging();
					this._ModifiedAccount = value;
					this.SendPropertyChanged("ModifiedAccount");
					this.OnModifiedAccountChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.WorkZoneDetail")]
	public partial class WorkZoneDetail
	{
		
		private int _Id;
		
		private int _WorkZoneId;
		
		private string _No;
		
		private string _NCFileName;
		
		private string _PathType;
		
		private System.Nullable<double> _ToolDia;
		
		private System.Nullable<double> _ToolConerR;
		
		private System.Nullable<double> _ToolLenth;
		
		private System.Nullable<double> _Tno;
		
		private System.Nullable<double> _StockAllowance;
		
		private System.Nullable<double> _Tolerance;
		
		private System.Nullable<double> _Spindll;
		
		private System.Nullable<double> _FeedRate;
		
		private System.Nullable<double> _Zmin;
		
		private System.Nullable<double> _CutDistance;
		
		private string _MachineTime;
		
		private string _Comment;
		
		private System.DateTime _CreateDate;
		
		private string _CreateAccount;
		
		private System.DateTime _ModifiedDate;
		
		private string _ModifiedAccount;
		
		public WorkZoneDetail()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WorkZoneId", DbType="Int NOT NULL")]
		public int WorkZoneId
		{
			get
			{
				return this._WorkZoneId;
			}
			set
			{
				if ((this._WorkZoneId != value))
				{
					this._WorkZoneId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_No", DbType="NVarChar(50)")]
		public string No
		{
			get
			{
				return this._No;
			}
			set
			{
				if ((this._No != value))
				{
					this._No = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NCFileName", DbType="NVarChar(100)")]
		public string NCFileName
		{
			get
			{
				return this._NCFileName;
			}
			set
			{
				if ((this._NCFileName != value))
				{
					this._NCFileName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PathType", DbType="NVarChar(100)")]
		public string PathType
		{
			get
			{
				return this._PathType;
			}
			set
			{
				if ((this._PathType != value))
				{
					this._PathType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ToolDia", DbType="Float")]
		public System.Nullable<double> ToolDia
		{
			get
			{
				return this._ToolDia;
			}
			set
			{
				if ((this._ToolDia != value))
				{
					this._ToolDia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ToolConerR", DbType="Float")]
		public System.Nullable<double> ToolConerR
		{
			get
			{
				return this._ToolConerR;
			}
			set
			{
				if ((this._ToolConerR != value))
				{
					this._ToolConerR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ToolLenth", DbType="Float")]
		public System.Nullable<double> ToolLenth
		{
			get
			{
				return this._ToolLenth;
			}
			set
			{
				if ((this._ToolLenth != value))
				{
					this._ToolLenth = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tno", DbType="Float")]
		public System.Nullable<double> Tno
		{
			get
			{
				return this._Tno;
			}
			set
			{
				if ((this._Tno != value))
				{
					this._Tno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StockAllowance", DbType="Float")]
		public System.Nullable<double> StockAllowance
		{
			get
			{
				return this._StockAllowance;
			}
			set
			{
				if ((this._StockAllowance != value))
				{
					this._StockAllowance = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tolerance", DbType="Float")]
		public System.Nullable<double> Tolerance
		{
			get
			{
				return this._Tolerance;
			}
			set
			{
				if ((this._Tolerance != value))
				{
					this._Tolerance = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Spindll", DbType="Float")]
		public System.Nullable<double> Spindll
		{
			get
			{
				return this._Spindll;
			}
			set
			{
				if ((this._Spindll != value))
				{
					this._Spindll = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FeedRate", DbType="Float")]
		public System.Nullable<double> FeedRate
		{
			get
			{
				return this._FeedRate;
			}
			set
			{
				if ((this._FeedRate != value))
				{
					this._FeedRate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zmin", DbType="Float")]
		public System.Nullable<double> Zmin
		{
			get
			{
				return this._Zmin;
			}
			set
			{
				if ((this._Zmin != value))
				{
					this._Zmin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CutDistance", DbType="Float")]
		public System.Nullable<double> CutDistance
		{
			get
			{
				return this._CutDistance;
			}
			set
			{
				if ((this._CutDistance != value))
				{
					this._CutDistance = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MachineTime", DbType="NChar(10)")]
		public string MachineTime
		{
			get
			{
				return this._MachineTime;
			}
			set
			{
				if ((this._MachineTime != value))
				{
					this._MachineTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comment", DbType="NVarChar(255)")]
		public string Comment
		{
			get
			{
				return this._Comment;
			}
			set
			{
				if ((this._Comment != value))
				{
					this._Comment = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime NOT NULL")]
		public System.DateTime CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this._CreateDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateAccount", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CreateAccount
		{
			get
			{
				return this._CreateAccount;
			}
			set
			{
				if ((this._CreateAccount != value))
				{
					this._CreateAccount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedDate", DbType="DateTime NOT NULL")]
		public System.DateTime ModifiedDate
		{
			get
			{
				return this._ModifiedDate;
			}
			set
			{
				if ((this._ModifiedDate != value))
				{
					this._ModifiedDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedAccount", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ModifiedAccount
		{
			get
			{
				return this._ModifiedAccount;
			}
			set
			{
				if ((this._ModifiedAccount != value))
				{
					this._ModifiedAccount = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
